In [1]:
# In your numpy-pandas-visualization-exercises repo, 
# create a file named numpy_exercises.py for this exercise

In [2]:
import numpy as np

In [3]:
# Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
# 1. How many negative numbers are there?
a[a < 0] # This will find all values in a that are less than 0
neg_num_len = len(a[a < 0]) #This gives a number of the amount of values that are less than 0

print(f' There are {neg_num_len} negative numbers.')

 There are 4 negative numbers.


In [5]:
# 2. How many positive numbers are there?
a[a > 0] # This will find all values in a that are more than 0
pos_num_len = len(a[a > 0]) #This gives a number of the amount of values that are more than 0
print(f' There are {pos_num_len} positive numbers.')

 There are 5 positive numbers.


In [6]:
# 3. How many even positive numbers are there?

# the & operator allows me to assure that multiple conditions must be met, similar to the 'and' function
a[(a > 0) & (a % 2 == 0)]
count_even_and_pos_nums = len(a[(a > 2) & (a % 2 == 0)])
print(f' There are {count_even_and_pos_nums} positive and even numbers.')

 There are 3 positive and even numbers.


In [7]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
a_plus_3 = a + 3
a_plus_3
amount_of_pos_plus_3 = len(a_plus_3[a_plus_3 > 0])

print(f' There are {amount_of_pos_plus_3} positive numbers after adding 3 to each data point')

 There are 10 positive numbers after adding 3 to each data point


In [8]:
# 5. If you squared each number, what would the new mean and standard deviation be?
a_squared = a ** 2
a_squared

new_mean = np.mean(a_squared) #Numpy will find the mean of the squared values using the variable i made for the squared values
new_std = np.std(a_squared) #Numpy will find the mean of the standard deviation using the variable i made for the squared values
print(f'The new mean is {new_mean}')
print(f'The new standard deviation is {new_std}')

The new mean is 74.0
The new standard deviation is 144.0243035046516


In [9]:
# 6. A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.


a_mean = np.mean(a) # The mean of the original array is 3.0

centered_data = a - a_mean # Now to center the data

np.mean(centered_data) #Running the mean of the centered data will allow me to check if i did everything correct
# The mean of the centered data is 0 so the data has been centered.

0.0

In [10]:
# 7.Calculate the z-score for each data point.
std = np.std(a)

z_score = (a - a_mean)/std
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [11]:
# 8. Copy the setup and exercise directions from
# More Numpy Practice into your numpy_exercises.py
# and add your solutions.

In [12]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
# Use python's built in functionality/operators to determine the following:

In [14]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = np.sum(a)
sum_of_a

55

In [15]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = np.min(a)
min_of_a

1

In [16]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = np.max(a)
max_of_a

10

In [17]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = np.mean(a)
mean_of_a

5.5

In [18]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = np.product(a)
product_of_a

3628800

In [19]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

#Use list comprehension for this one so that the variable creates a seperate list holding the squared values from a
squares_of_a = [num ** 2 for num in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [20]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

#Use list comprehension for this one so that the variable creates a seperate list holding the odd numbers from a
odds_in_a = [num for num in a if num % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

In [21]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = [num for num in a if num % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [22]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [23]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
    ]

In [24]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**

#sum_of_b = 0
#for row in b:
#    sum_of_b += sum(row)

b = np.array(b) # start by making b a 2x3 array 
sum_of_b = np.sum(b) #np.sum will add up all values in b
print(sum_of_b)

33


In [25]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

min_of_b = np.min(b) #np.min will determine the smallest value automatically
min_of_b

3

In [26]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(b) #np.max will determine the largest value automatically
max_of_b

8

In [27]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(b) #np.mean will calculate the mean of b automatically
mean_of_b

5.5

In [28]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

product_of_b = np.product(b) #np.product multiplies all of the values in b to eachother and gives the result
product_of_b

20160

In [29]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [30]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

odds_in_b = b[b % 2 == 1] # We can pass a boolean mask that has set odd numbers to True, and then use that to index the array
print(odds_in_b)

[3 5 7]


In [31]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

evens_in_b = b[b % 2 == 0] # We can pass a boolean mask that has set odd numbers to True, and then use that to index the array
print(evens_in_b)

[4 6 8]


In [32]:
# Exercise 9 - print out the shape of the array b.

print(b.shape) # The shape gives us the (number of rows, number of columns) as a tuple 

(2, 3)


In [33]:
# Exercise 10 - transpose the array b.

np.transpose(b) # np.transpose() turns our A x B array into a B x A array

array([[3, 6],
       [4, 7],
       [5, 8]])

In [34]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

np.reshape(b, 6) # np.reshape(array, shape) converts our array into a 1x6

array([3, 4, 5, 6, 7, 8])

In [35]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

np.reshape(b, (6, 1)) #np.reshape(array, shape) converts our array into a shape represented by a tuple

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [36]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [37]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)

print('Min:',np.min(c), 'Max:',np.max(c), 'Sum:', np.sum(c),'Product:', np.product(c))

Min: 1 Max: 9 Sum: 45 Product: 362880


In [38]:
# Exercise 2 - Determine the standard deviation of c.

print('Standard Deviation:' ,np.std(c))

Standard Deviation: 2.581988897471611


In [39]:
# Exercise 3 - Determine the variance of c.

print(np.var(c))

6.666666666666667


In [40]:
# Exercise 4 - Print out the shape of the array c

print(c.shape)

(3, 3)


In [41]:
# Exercise 5 - Transpose c and print out transposed result.

print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [42]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c, c)
# The dot product array can be calculated with np.dot(), with each array passed in as arguments

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [43]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

np.sum(c * np.transpose(c)) # We can use both the np.transpose() function and the np.sum() function

261

In [44]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

np.product(c * np.transpose(c)) # Same as before, but we are using np.product() instead of np.sum()

131681894400

In [51]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

In [52]:
# Exercise 1 - Find the sine of all the numbers in d

# In[89]:


np.sin(d) #You can use numpys np.sin() function instead of having to import math

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [53]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d) #You can use numpys np.cos() function instead of having to import math

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [54]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d) #You can use numpys np.tan() function instead of having to import math

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [57]:
# Exercise 4 - Find all the negative numbers in d

d[d < 0]
d_neg_num_len = len(d[d < 0])
print(f' There are {d_neg_num_len} negative numbers.')

 There are 4 negative numbers.


In [58]:
# Exercise 5 - Find all the positive numbers in d

d[d > 0]
d_pos_num_len = len(d[d > 0])
print(f' There are {d_pos_num_len} positive numbers.')

 There are 12 positive numbers.


In [59]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [60]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d)) # np.unique() gives us all of the unique elements of the selected array

11

In [64]:
# Exercise 8 - Print out the shape of d.

print(d.shape) # By using the array.shape function will produce our tuple of (rows, columns)

(3, 6)


In [68]:
# Exercise 9 - Transpose and then print out the shape of d.

print(np.transpose(d).shape)

(6, 3)


In [69]:
# Exercise 10 - Reshape d into an array of 9 x 2

np.reshape(d, (9, 2)) # We can use the reshape() function to change the number of rows x columns of the array, through the list will still read the same from left to right

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])